# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LoopBackCall' do
pod 'KMSClient', '1.0.5'
pod 'ReactiveCocoa', '2.5'
pod 'libjingle_peerconnection'
end

