# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'LoopBackCall' do
pod 'UIImage+Additions', '2.1.0'
pod 'MBProgressHUD', '0.9.1'
pod 'KMSClient', '1.0.5'
pod 'ReactiveCocoa', '2.5'
pod 'CGSizeAspectRatioTool', '1.0'
pod 'libjingle_peerconnection'

end

