# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

target 'LoopBackCall' do
pod 'UIImage+Additions', '2.1.0'
pod 'MBProgressHUD', '0.9.1'
pod 'KMSClient', '1.0.5'
pod 'ReactiveCocoa', '2.5'
pod 'CGSizeAspectRatioTool', '1.0'
#pod 'WebRTC_framework', '10842.2.3'
pod 'libjingle_peerconnection'
end

