# Uncomment this line to define a global platform for your project
workspace 'KMSWebRTC.xcworkspace'
platform :ios, '8.0'
use_frameworks!

def shared_pods
   pod 'ReactiveObjC', '3.0.0'
   pod 'KMSClient', '1.1.3'
   pod 'MantleNullValuesOmit', '0.0.2'
   pod 'Mantle', '2.1.0'
   pod 'WebRTC', '61.5.19063'
end

target 'KMSWebRTC' do
    project 'KMSWebRTC.xcodeproj'
    shared_pods
end

target 'LoopBackCall' do
    project 'LoopBackCall.xcodeproj'
    pod 'UIImage+Additions', '2.1.0'
    pod 'MBProgressHUD', '0.9.1'
    pod 'CGSizeAspectRatioTool', '1.0'
    shared_pods
end
